Jdp210201-05
interceptor2048/projekt-jdp-2102-01 pull request #1
Opened 2021-02-26 16:58 UTC by Ktubbo

- Dodany UserController, 
- Dodany UserDto,
- Dodany do specs ERD Entity Diagram

2021-02-26 17:51 UTC, wisniewskimateusz requested changes
1. createUser() why PUT instead od POST?
2. createUser() nothing return for tests, why it is empty?

2021-02-26 18:11 UTC, Ktubbo commented
>     1. createUser() why PUT instead od POST?
>     2. createUser() nothing return for tests, why it is empty?
1. PUT and POST change its places
2. Return nothing, because it is void method. In postman server will return empty Json.

2021-02-26 22:12 UTC, Bauaser-kun commented
generateRandomKey - opis w specyfikacji endpointu mówi o wygenerowaniu klucza po podaniu danych użytkownika, na moje metoda powinna zwracać Long i wymagać parametrów z UserDto. (@RequestBody UserDto)

2021-02-26 22:20 UTC, Bauaser-kun commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    public UserDto generateRandomKey(UserDto userDto) {
generateRandomKey - opis w specyfikacji endpointu mówi o wygenerowaniu klucza po podaniu danych użytkownika, na moje metoda powinna zwracać Long i wymagać parametrów z UserDto. (@ RequestBody UserDto)
And to not get rusty with English once again the same ;P: endpoints specs states about generating new key based on User's data, as for me it means the method should return Long and request params from UserDto.

2021-02-26 22:26 UTC, Ktubbo commented on src/main/java/com/kodilla/ecommercee/user/controller/UserController.java
> +    public UserDto generateRandomKey(UserDto userDto) {
I have to remind that is only EMPTY cotroller, sending json in postman returns userDto with "new random key" in last field.

2021-02-26 22:27 UTC, Ktubbo commented
> generateRandomKey - opis w specyfikacji endpointu mówi o wygenerowaniu klucza po podaniu danych użytkownika, na moje metoda powinna zwracać Long i wymagać parametrów z UserDto. (@ RequestBody UserDto)
> And to not get rusty with English once again the same ;P: endpoints specs states about generating new key based on User's data, as for me it means the method should return Long and request params from UserDto.

2021-02-27 10:43 UTC, Ktubbo commented
- Added @requestbody annotation,
- Changed RequestMapping methods,
- Added info about created user

2021-03-01 12:16 UTC, lukkra1989 approved these changes

2021-03-01 12:34 UTC, wisniewskimateusz approved these changes

2021-03-01 12:34 UTC, merged