Jdp210201 1
interceptor2048/projekt-jdp-2102-01 pull request #2
Opened 2021-02-26 22:01 UTC by Bauaser-kun

2021-02-26 22:35 UTC, Ktubbo approved these changes, later dismissed

2021-02-26 22:41 UTC, Ktubbo requested changes
Edit (01.03): I think that you should not push Product class, because @Maciek2k3 has made it properly in _Product entity_ branch.

2021-02-27 07:45 UTC, Maciek2k3 reviewed
https://guides.github.com/features/mastering-markdown/

2021-02-27 07:45 UTC, Maciek2k3 commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    }
I know that is void, but don't we should add @RequestParam with Id to @DeleteMappling.

2021-02-27 10:22 UTC, wisniewskimateusz commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    }
yes, (**@RequestParam Long id**)

2021-03-01 12:50 UTC, wisniewskimateusz submitted a review, later dismissed
1. In deleteProduct should by (@RequestParam Long id)
2. In ProductDao int id -> Long id

2021-03-01 13:11 UTC, Ktubbo approved these changes

2021-03-01 14:23 UTC, Maciek2k3 approved these changes

2021-03-01 14:51 UTC, merged