Product entity
interceptor2048/projekt-jdp-2102-01 pull request #3
Opened 2021-02-27 12:10 UTC by Maciek2k3

Created product entity, since is connected with Cart/Groups/OrderItem, I've created basic class only for correlations, if they are working properly

2021-03-01 05:58 UTC, Ktubbo reviewed
I think that ajax in frontend will be looking for those names in Json.

> {
>     "id": 1,
>     "name": "kurtka zimowa",
>     "description": "Pellentesque (...) purus.",
>     "price": 100,
>     "groupId": "1"
> }

2021-03-01 10:53 UTC, Maciek2k3 commented
> I think that ajax in frontend will be looking for those names in Json.
> 
> > {
> > "id": 1,
> > "name": "kurtka zimowa",
> > "description": "Pellentesque (...) purus.",
> > "price": 100,
> > "groupId": "1"
> > }

2021-03-01 11:17 UTC, Ktubbo commented
I think that those:

```
@Column(name = "productId")
@Column(name = "productName")
@Column(name = "productDescription")
```
should be named like this:

```
{
"id": 1,
"name": "kurtka zimowa",
"description": "Pellentesque (...) purus.",
"price": 100,
"groupId": "1"
}
```

2021-03-01 14:17 UTC, Maciek2k3 commented
Yes, sorry you are correct, I will update ASAP

2021-03-01 15:59 UTC, Ktubbo commented on src/main/java/com/kodilla/ecommercee/domian/Product.java
> +    private Groups groups;
I think that this class should be named `Group`.

2021-03-01 17:39 UTC, Ktubbo approved these changes

2021-03-01 18:42 UTC, Bauaser-kun commented on src/main/java/com/kodilla/ecommercee/domian/Product.java
> +    private String productDescription;
Shouldn't we ensure that the product will always have some kind of description? (Adding @ NotNull annotation)

2021-03-02 06:49 UTC, Ktubbo submitted a review, later dismissed

2021-03-02 06:49 UTC, Ktubbo commented on src/main/java/com/kodilla/ecommercee/domian/Product.java
> +    private String productDescription;
I will not agree. I think there should be possibility to have empty description.

2021-03-02 14:12 UTC, Bauaser-kun commented on src/main/java/com/kodilla/ecommercee/domian/Product.java
> +    private String productDescription;
Ok. It was just a suggestion anyway, no changes requested

2021-03-02 14:16 UTC, Bauaser-kun requested changes
Have you created repository?
https://snipboard.io/3yYfvz.jpg

2021-03-02 18:00 UTC, Ktubbo approved these changes

2021-03-02 18:52 UTC, Bauaser-kun approved these changes

2021-03-02 19:53 UTC, merged