OrderController, OrderDto, Order created
interceptor2048/projekt-jdp-2102-01 pull request #7
Opened 2021-03-01 18:40 UTC by pawelski85

2021-03-01 19:11 UTC, Bauaser-kun requested changes

2021-03-01 19:11 UTC, Bauaser-kun commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +}
Based on our ERD Dto should have a bit more fields (Long userId, booleans paid, verified, sent)

2021-03-04 15:47 UTC, Bauaser-kun approved these changes

2021-03-04 17:24 UTC, lukkra1989 approved these changes

2021-03-04 18:54 UTC, merged