JDP210201-3
interceptor2048/projekt-jdp-2102-01 pull request #8
Opened 2021-03-01 19:43 UTC by wisniewskimateusz

2021-03-01 20:21 UTC, Bauaser-kun requested changes

2021-03-01 20:21 UTC, Bauaser-kun commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +
Should be  ProductDto instead of List

2021-03-01 20:29 UTC, wisniewskimateusz commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +
but this added many Products to Cart, and the isn't field quantity i Product class. So how to add many products (the same) to cart?

2021-03-01 21:30 UTC, Ktubbo commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +
But where you want to build this list of product? Imagine online shop, you pick a product, choose quantity of it and press "add to cart". Then products are added to a cart. I think that you will need, cartId to get specific Cart, productId to add specific product to a Cart and quantity of a product which you want to add.

2021-03-01 22:01 UTC, wisniewskimateusz commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +
`addProductToCart(@RequestParam Long cartId, @RequestParam Long productId)`

2021-03-02 12:30 UTC, Ktubbo requested changes

2021-03-02 12:30 UTC, Ktubbo commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    }
Same thing here, you need to indicate specific cart and delete specific product from it.

2021-03-02 13:08 UTC, Bauaser-kun approved these changes

2021-03-02 21:18 UTC, Ktubbo approved these changes

2021-03-02 21:21 UTC, merged